# permissions for end users to edit microservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: expose-operator-sdk
    app.kubernetes.io/managed-by: kustomize
  name: microservice-editor-role
rules:
- apiGroups:
  - api.example.com
  resources:
  - microservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.example.com
  resources:
  - microservices/status
  verbs:
  - get
